### PR TITLE
Lab 1

### PR DESCRIPTION
**Pull request by trypuzz**
Just a try to add request -_-

### CODE REVIEW

**Comment by amarjin6** [comment]
Perfect code!

**Comment by WildTiger404** [comment]
> Perfect code!

Is it, so?

**Comment by WildTiger404** [comment]
create gitignore file and delete obj folder

**Comment by WildTiger404** [comment]
Is this code is ready for my review?

**Comment by trypuzz** [comment]
> Is this code is ready for my review?

of course not.  development is still in progress, will be completed soon

**Comment by amarjin6** [comment]
Don't use google translate for communication!

**Pull request closed without merging**
